### ISSUE TITLE
Implement Presence

### ISSUE THREAD

**Issue by Mazyod** [Mazyod/PhoenixSharp#1]
Presence class is currently just an empty stub. It should be implemented with tests based on the JS client.

**Comment by jonathanleang** [comment]
not sure where to ask questions or message you.

is this project ready for use by production game?  

Thank you.

**Comment by Mazyod** [comment]
@jonathanleang you can simply just open an issue!

Yes, as described in the readme, I have a game in production, and it's performing pretty well so far. See readme for link to the game (macOS, iOS, Android).

**Comment by Shivang44** [comment]
What does this mean? Will presence not working on the server side? I.e., when a client connects, I can call `track` on them right? What does the client have to do with this? I'm new to phoenix channels

**Comment by Mazyod** [comment]
I think presence is different that connecting to channels, but I could be wrong. I haven't used presence yet, so I am not the best person to answer this question 😅
