### ISSUE TITLE
How to use it with unity3D

### ISSUE THREAD

**Issue by LordOkami** [Mazyod/PhoenixSharp#15]
Hi, I'm trying to use the library with Unity3D and I'm having multiple compilation errors, do you have an example proyect in unity to get started with your library?

Thanks in advance

**Comment by Shivang44** [comment]
> I'm having multiple compilation errors

Can you output the errors? One thing I did was delete anything inside vendor that was causing a compilation error (BestHTTP folder, NUnit, Nsubstitute). After that I didn't have any errors.

**Comment by Mazyod** [comment]
I personally add this project as a submodule to my Unity project repo under `Vendor` folder, and then use this script to copy specific files into the Unity Assets folder:

```python
#!/usr/local/bin/python3

import shutil
import os

src_dir = "./Vendor/PhoenixSharp/Phoenix"
dst_dir = "./KoD-Unity/Assets/Vendor/PhoenixSharp/"
files = filter(lambda f: f.endswith(".cs"), os.listdir(src_dir))
files = map(lambda f: os.path.join(src_dir, f), files)

for f in files:
	shutil.copy(f, dst_dir)
```

**Comment by LordOkami** [comment]
Thank you for your fast response! :), I'm afraid I'm doing wrong, I'm a total newbie in Unity and C#, I've just copied the folder PhoenixSharp into my proyect:
![image](https://user-images.githubusercontent.com/1300224/67617587-d20a3800-f7e4-11e9-9906-be43f4fb3966.png)
And there are the errors on the console:
![image](https://user-images.githubusercontent.com/1300224/67617542-5dcf9480-f7e4-11e9-8219-d4a80d954663.png)

I'll try to add the proyect as submodule and run your script to copy the files, thanks a million :)

**Comment by LordOkami** [comment]
Finally I've a socket connection working.

Thanks for your help! :)
